#!/bin/sh

. $GITDIR/hooks/functions.bash

process()
{
    file="$1"
    
    mv "$file" "$file.orig"
    cat "$file.orig" | sed 's/^\([\t]*\)    /\1\t/g'  | sed 's/^\([\t]*\) \{1,3\}\t/\1\t/g' > "$file"
    rm "$file.orig"
    git add "$file"
}

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

changed_files=$(git diff-index --cached $against | grep -i -E '[MA]	.*\.(c|cc|cpp|h|hh)$' | cut -d'	' -f 2)

if [ -n "$changed_files" ]
then
    echo "$changed_files" | while read file
    do
        echo "process \"$file\""
        process "$file"
    done    
fi

exit 0
