.TH "gh_xen_decrypt" "1" "" "" ""
.SH "NAME"
gh_xen_decrypt \- Tool for decrypting Guitar Hero xen files
.SH "SYNOPSIS"
\fBgh_xen_decrypt\fR input.xen output
.TP
\fBinput.xen\fR
Xen source file
.TP
\fBoutput\fR
destination file
.SH "DESCRIPTION"
Tool for decrypting Guitar Hero xen files
.SH "SEE ALSO"
\fIperformous\fR(6)
