.TH "ss_chc_decode" "1" "" "" ""
.SH "NAME"
ss_chc_decode \- Tool for decoding Singstar CHC (melody cache) files
.SH "SYNOPSIS"
\fBss_chc_decode\fR chc_file key1 key2 key3 key4 track_id
.TP
\fBchc_file\fR
Singstar melody cache file
.TP
\fBkey1 to key4\fR
keys to decode the cache file
.TP
\fBtrack_id\fR
Singstar track id to extract
.SH "DESCRIPTION"
Tool for decrypting Singstar CHC files.
.SH "SEE ALSO"
\fIperformous\fR(6)
