.TH "ss_cover_conv" "1" "" "" ""
.SH "NAME"
ss_cover_conv \- Tool for converting Singstar song cover
.SH "SYNOPSIS"
\fBss_cover_conv\fR [\-h|\-\-help] pak_file track_id output_image
.TP
\fB\-h\fR [ \fB\-\-help\fR ]
you are viewing it
.TP
\fBpak_file\fR
Singstar Pak file to look in
.TP
\fBtrack_id\fR
Singstar track id to extract
.TP
\fBoutput_image\fR
Output image (format will be automatically detected)
.SH "DESCRIPTION"
Tool for converting internal Singstar song cover (TX2 format) into a standard format
.SH "SEE ALSO"
\fIperformous\fR(6)
