.TH "ss_ipu_conv" "1" "" "" ""
.SH "NAME"
ss_ipu_conv \- Tool for converting Singstar videos
.SH "SYNOPSIS"
\fBss_ipu_conv\fR infile.ipu outfile.m2v
.TP
\fBinfile.ipu\fR
Singstar ipu video file
.TP
\fBoutfile.m2v\fR
Video output file (MPEG2-Video)
.SH "DESCRIPTION"
Tool for converting Singstar videos
.SH "SEE ALSO"
\fIperformous\fR(6)
