# Find libsamplerate

find_path(LIBSAMPLERATE_INCLUDE_DIR samplerate.h)

set(LIBSAMPLERATE_NAMES ${LIBSAMPLERATE_NAMES} samplerate libsamplerate)
find_library(LIBSAMPLERATE_LIBRARY NAMES ${LIBSAMPLERATE_NAMES} PATH)

if (LIBSAMPLERATE_INCLUDE_DIR AND LIBSAMPLERATE_LIBRARY)
    set(LIBSAMPLERATE_FOUND TRUE)
endif (LIBSAMPLERATE_INCLUDE_DIR AND LIBSAMPLERATE_LIBRARY)

if (LIBSAMPLERATE_FOUND)
    if (NOT LibSampleRate_FIND_QUIETLY)
        message (STATUS "Found LibSampleRate: ${LIBSNDFILE_LIBRARY}")
    endif (NOT LibSampleRate_FIND_QUIETLY)
else (LIBSAMPLERATE_FOUND)
    if (LibSampleRate_FIND_REQUIRED)
        message (FATAL_ERROR "Could not find samplerate")
    endif (LibSampleRate_FIND_REQUIRED)
endif (LIBSAMPLERATE_FOUND)
