.TH "ss_adpcm_decode" "1" "" "" ""
.SH "NAME"
ss_adpcm_decode \- Tool for converting ADPCM Singstar audio format to WAV
.SH "SYNOPSIS"
\fBss_adpcm_decode\fR [archive.pak] input.mib output.wav
.TP
[ \fBarchive.pak\fR ]
Optional Singstar archive name to look in
.TP
\fBinput.mib\fR
ADPCM source file
.TP
\fBoutput.wav\fR
WAV destination file
.SH "DESCRIPTION"
Tool for converting ADPCM Singstar audio format to WAV
.SH "SEE ALSO"
\fIperformous\fR(6)
