.TH "ss_ipu_decode" "1" "" "" ""
.SH "NAME"
ss_ipu_decode \- Tool for decoding Singstar videos
.SH "SYNOPSIS"
\fBss_ipu_decode\fR input output
.TP
\fBinput\fR
Singstar ipu video file
.TP
\fBoutput\fR
Video output file
.SH "DESCRIPTION"
Tool for decoding Singstar videos
.SH "SEE ALSO"
\fIperformous\fR(6)
