.TH "ss_pak_extract" "1" "" "" ""
.SH "NAME"
ss_pak_extract \- Tool for reading general PAK files (used by Singstar)
.SH "SYNOPSIS"
.TP
\fBss_pak_extract\fR [\-h|\-\-help] file.pak \-\-extract [files]
Extract \fBfiles\fR from \fBfile.pak\fR pak file.
.TP
\fBss_pak_extract\fR file.pak \-\-dump file
Dump \fBfile\fR content from \fBfile.pak\fR pak file to stdout.
.TP
\fBss_pak_extract\fR file.pak \-\-list
List files from \fBfile.pak\fR pak file to stdout.
.SH "DESCRIPTION"
Tool for reading general PAK files (used by Singstar)
.SH "SEE ALSO"
\fIperformous\fR(1)
