.TH "" "" "" "" ""
.SH "NAME"
performous\-tools \- Tools for Performous karaoke game
.SH "SYNOPSIS"
\fBss_extract\fR [\-h|\-\-help] [\-\-dvd arg] [\-l|\-\-list] [\-\-song arg] [\-\-video arg] [\-\-audio arg]
\fBss_adpcm_decode\fR [\-h|\-\-help] [archive.pak] input.mib output.wav
\fBss_cover_conv\fR [\-h|\-\-help] [pak_file] [track_id] [output_image]
\fBss_ipu_conv\fR [\-h|\-\-help] infile.ipu outfile.m2v
\fBss_ipu_decode\fR [\-h|\-\-help] input output
\fBss_pak_extract\fR [\-h|\-\-help] file.pak \-\-extract [files]
\fBss_pak_extract\fR file.pak \-\-dump file
\fBss_pak_extract\fR file.pak \-\-list
.SH "DESCRIPTION"
Tools for converting original Singstar DVDs to the format used by Performous.
.SH "SEE ALSO"
\fIperformous\fR(1)
