#!/bin/bash

dir=$(dirname "$0")
export PATH=$PATH:"$dir"
export FONTCONFIG_PATH="$dir/../Resources/etc/fonts"
# somehow this doesn't work on a MacBookPro under 10.5.8:
#performous 2>&1 --pdev pa19 --mics pa19
# TODO: might be a good idea to turn-off all console output
performous
