name: Build MacOS Package

on:
  # Run on a schedule to get monthly updates
  schedule:
    - cron: "0 0 28 * *"

  # Run when called from other workflows
  workflow_call:
    inputs:
      package_complete_version:
        description: 'The output of the complete_version of the "determine_version" job from the build_and_release.yml workflow'
        required: true
        type: string
      release_upload_url:
        description: 'The output of the "create_release" job from the build_and_release.yml workflow'
        required: true
        type: string

jobs:
  # Create the MacOS dmg
  MacOS_Packages:
    name: Create MacOS dmg
    runs-on: macos-latest
    steps:
      - name: Checkout Git
        id: checkout_git
        uses: actions/checkout@v3
        with:
          path: performous


      # brew fetch runs downloads in parallel, which is faster
      # than letting install do it
      - name: Fetch Dependencies
        id: fetch_deps
        run: |
          brew fetch --deps boost cmake ffmpeg@4 help2man icu4c portaudio\
            portmidi opencv libepoxy librsvg libxml++3 sdl2 dylibbundler\
            aubio fftw glm nlohmann-json fmt

      - name: Install Dependencies
        id: install_deps
        run: |
           brew install boost cmake ffmpeg@4 help2man icu4c portaudio\
            portmidi opencv libepoxy librsvg libxml++3 sdl2 dylibbundler\
            aubio fftw glm nlohmann-json fmt
           brew link --force --overwrite ffmpeg@4

      - name: Build package
        id: build_package
        run: |
          cd performous/osx-utils
          # This export is required because the variable is consumed by the 
          # MacOS build script to set the version correctly
          export PACKAGE_VERSION=${{ inputs.package_complete_version }}
          echo $PACKAGE_VERSION
          chmod +x ./performous-app-build.sh
          WORK_DIR=$(pwd)
          mkdir -p out
          export PERFORMOUS_OUTPUT_DIR="${WORK_DIR}/out"
          ./performous-app-build.sh
          PACKAGE_PATH=$(ls ${PERFORMOUS_OUTPUT_DIR}/Performous*.dmg)
          PACKAGE_NAME=$(echo ${PACKAGE_PATH} | sed 's/\(Performous\).*$/\1/')
          PACKAGE_SUFFIX=$(echo ${PACKAGE_PATH} | sed 's/^.*\(.\{4\}\)/\1/')
          NEW_PACKAGE_NAME="${PACKAGE_NAME}-${PACKAGE_VERSION}${PACKAGE_SUFFIX}"
          MASTER_NEW_PACKAGE_NAME="${PACKAGE_NAME}-latest${PACKAGE_SUFFIX}"
          cp ${PACKAGE_PATH} ${MASTER_NEW_PACKAGE_NAME}
          mv ${PACKAGE_PATH} ${NEW_PACKAGE_NAME}
          ARTIFACT_NAME=$( echo ${NEW_PACKAGE_NAME} | rev | cut -d '/' -f1 | rev)
          MASTER_ARTIFACT_NAME=$( echo ${MASTER_NEW_PACKAGE_NAME} | rev | cut -d '/' -f1 | rev)
          echo "ARTIFACT_PATH=${NEW_PACKAGE_NAME}" >> ${GITHUB_ENV}
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> ${GITHUB_ENV}
          echo "MASTER_ARTIFACT_PATH=${MASTER_NEW_PACKAGE_NAME}" >> ${GITHUB_ENV}
          echo "MASTER_ARTIFACT_NAME=${MASTER_ARTIFACT_NAME}" >> ${GITHUB_ENV}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

      - name: Upload artifact with unified name
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.MASTER_ARTIFACT_NAME }}
          path: ${{ env.MASTER_ARTIFACT_PATH }}

      - name: Upload artifacts to tagged release
        id: upload_assets
        if: ${{ github.event_name != 'pull_request' && github.ref_type == 'tag' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.release_upload_url }}
          asset_path: ${{ env.ARTIFACT_PATH }}
          asset_name: ${{ env.ARTIFACT_NAME }}
          asset_content_type: application/octet-stream
