name: Build MacOS Package

on:
  # Run when called from other workflows
  workflow_call:
    inputs:
      package_complete_version:
        description: 'The output of the complete_version of the "determine_version" job from the build_and_release.yml workflow'
        required: true
        type: string
      release_id:
        description: 'The output of the "create_release" job from the build_and_release.yml workflow'
        required: true
        type: string
    secrets:
      NGROK_SSH_TOKEN:
        description: 'Token for SSH debug'
        required: false
      NGROK_SSH_PASS:
        description: 'Pass for SSH debug'
        required: false

jobs:
  # Create the MacOS dmg
  MacOS_Packages:
    name: Create MacOS dmg
    runs-on: macos-13
    env:
      MACOS_DEPS: >-
        aubio
        boost
        cairo
        cmake
        cpprestsdk
        dylibbundler
        ffmpeg@7
        fftw
        fmt
        fontconfig
        freetype
        glm
        googletest
        help2man
        icu4c
        libepoxy
        librsvg
        libxml++3
        nlohmann-json
        opencv
        openssl
        pango
        pkg-config
        portaudio
        portmidi
        sdl2
    steps:
      - name: Checkout Git
        id: checkout_git
        uses: actions/checkout@v4
        with:
          path: performous

      - name: Start SSH session
        if: false
        id: ssh_debug
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_SSH_TOKEN }}
          SSH_PASS: ${{ secrets.NGROK_SSH_PASS }}

      - name: "Update Brew"
        id: update_brew
        run: |
          brew update
      # brew fetch runs downloads in parallel, which is faster
      # than letting install do it
      - name: Fetch Dependencies
        id: fetch_deps
        run: |
          brew fetch --deps $MACOS_DEPS

      - name: Install Dependencies
        id: install_deps
        run: |
           brew unlink python
           brew install $MACOS_DEPS 2>&1
           #brew unlink boost@1.87
           #brew link --force boost@1.85

      - name: Build package
        id: build_package
        run: |
          cd performous/osx-utils
          chmod +x ./macos-bundler.py
          pip3 install -r ./macos-bundler-requirements.txt
          python3 ./macos-bundler.py --flat-output --package-version="${{ inputs.package_complete_version }}" --enable-webserver=on --enable-midi=on --enable-webcam=on --build-tests=on --target=12.0
          PACKAGE_PATH=$(ls "${{ github.workspace }}/performous/osx-utils/out/Performous-${{ inputs.package_complete_version }}.dmg")
          MASTER_PACKAGE_PATH="${{ github.workspace }}/performous/osx-utils/out/Performous-master[${{ inputs.package_complete_version }}].dmg"
          cp -v ${PACKAGE_PATH} ${MASTER_PACKAGE_PATH}
          echo "ARTIFACT_PATH=${PACKAGE_PATH}" >> ${GITHUB_ENV}
          echo "ARTIFACT_NAME=$(basename ${PACKAGE_PATH})" >> ${GITHUB_ENV}
          echo "MASTER_ARTIFACT_PATH=${MASTER_PACKAGE_PATH}" >> ${GITHUB_ENV}
          echo "MASTER_ARTIFACT_NAME=$(basename ${MASTER_PACKAGE_PATH})" >> ${GITHUB_ENV}
      - name: Run unittests directly called.
        run: |
          cd "${{ github.workspace }}/performous/build/testing"
          ./performous_test --gtest_filter=UnitTest*
      - name: Run unittests by ctest.
        run: |
          cd "${{ github.workspace }}/performous/build"
          make test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

      - name: Upload artifact with unified name
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MASTER_ARTIFACT_NAME }}
          path: ${{ env.MASTER_ARTIFACT_PATH }}

      - name: Upload artifacts to tagged release
        id: upload_assets
        if: ${{ github.event_name != 'pull_request' && github.ref_type == 'tag' }}
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ inputs.release_id }}
          file: ${{ env.ARTIFACT_PATH }}
